
services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresCont 
    restart: always
    environment:
      - POSTGRES_DB=notes
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
  noteencrypt_server:
    container_name: noteencrypt_server
    image: noteencrypt-server-img
    build:
      context: ./
      dockerfile: Dockerfile-server
    ports:
      - 8085:8085
    restart: always
    depends_on:
      - postgres_db
volumes:
  postgres_db:
    driver: local